configsVersion:
  version: 2.0.3-b7910
workshop:
  publishedID: 3622322952
  visibility: FriendsOnly
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: Additional fixes.
  tags:
  - Overworld
  - Campaign
  - Models
  - Textures
  texPreviewUpload: true
configEdits: 
textEdits:
  languages:
    English:
      sectors:
        overworld_provinces:
          text:
            province_g1_mod_01_desc:
              text: Sparsely populated highlands at the foot of the Sunset Walls. Full of snow and rare isotopes.
              textSource: 
            province_g1_mod_01_name:
              text: Rodlund
              textSource: 
assetBundles:
  bundleDefinitions:
  - enabled: true
    name: landscape_sample
    files:
    - path: Assets/User/Sources/mod_landscape_01/mod_landscape_01.prefab
libraryDLLs: 
extraFiles: 
