configsVersion:
  version: 2.1.0
workshop:
  publishedID: 3622322952
  visibility: FriendsOnly
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: Additional fixes.
  tags:
  - Overworld
  - Campaign
  - Models
  - Textures
  texPreviewUpload: true
configEdits: 
textEdits:
  languages:
    English:
      sectors:
        overworld_provinces:
          text:
            province_g1_mod_01_desc:
              text: Sparsely populated highlands at the foot of the Sunset Walls. Full of snow and rare isotopes.
              textSource: 
            province_g1_mod_01_name:
              text: Rodlund
              textSource: 
            province_g2_mod_02_desc:
              text: A sparsely populated plateau full of mineral extraction operations. The lone mountain in the middle of the province was the site of the biggest radio observatory in Fyrland before the invasion.
              textSource: 
            province_g2_mod_02_name:
              text: Ensamtberg
              textSource: 
assetBundles:
  bundleDefinitions:
  - enabled: true
    name: landscape_sample
    files:
    - path: Assets/User/Sources/mod_landscape_01/mod_landscape_01.prefab
    - path: Assets/User/Sources/mod_landscape_02/mod_landscape_02.prefab
libraryDLLs: 
extraFiles: 
