workshop:
  publishedID: 
  visibility: Private
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: Initial upload.
  tags: []
  texPreviewUpload: true
configEdits: 
textEdits: 
assetBundles: 
libraryDLLs: 
extraFiles: 
