workshop: 
configEdits:
  dataLinkers:
  - type: DataLinkerSettingsOverworld
    file:
      edits:
      - path: customStartAllowed
        value: true
        operation: Override
  dataMultiLinkers:
  - type: DataMultiLinkerOverworldCampaignStart
    edits:
    - key: test
      removed: false
      edits:
      - path: hidden
        value: true
        operation: Override
  - type: DataMultiLinkerOverworldInteraction
    edits:
    - key: hg_base_entry
      removed: false
      edits:
      - path: steps.main.optionsReused
        value: '!d'
        operation: Override
      - path: steps.main.optionsReused.0
        value: '!+'
        operation: Override
      - path: steps.main.optionsReused.0.keyInteraction
        value: mod_campaign_frontline_additions
        operation: Override
      - path: steps.main.optionsReused.0.keyStep
        value: main
        operation: Override
      - path: steps.main.optionsReused.0.keyOption
        value: campaign_options
        operation: Override
    - key: hg_base_exit
      removed: false
      edits:
      - path: steps.main.optionsReused
        value: '!d'
        operation: Override
      - path: steps.main.optionsReused.0
        value: '!+'
        operation: Override
      - path: steps.main.optionsReused.0.keyInteraction
        value: mod_campaign_frontline_additions
        operation: Override
      - path: steps.main.optionsReused.0.keyStep
        value: main
        operation: Override
      - path: steps.main.optionsReused.0.keyOption
        value: campaign_options
        operation: Override
textEdits:
  languages:
    English:
      sectors:
        overworld_campaign:
          text:
            mod_campaign_01__header:
              text: Starting up
              textSource: 
            mod_campaign_01__text:
              text: Get your bearings and pick a destination.
              textSource: 
            mod_campaign_02__header:
              text: Punching through
              textSource: 
            mod_campaign_02__text:
              text: Keep hitting the enemy where it hurts. Advance through Fyrland to rendezvous with allied forces.
              textSource: 
        overworld_interaction:
          text:
            mod_campaign_arrival_01__s_step_01_main:
              text: One by one, red dots light up the map in the briefing room, warning about converging patrols and enemy positions. The base nears the frontline. They won't be able to stop you.
              textSource: 
            mod_campaign_frontline_additions__s_main_op_campaign_options_header:
              text: Campaign options
              textSource: 
            mod_campaign_start__s_main_header:
              text: RECEIVING INTEL...
              textSource: 
            mod_campaign_start__s_main_main:
              text: After days in the dark navigating the Northern Supercollider tunnels, your mobile base finally emerges into the light. You are deep behind enemy lines, in the Keystone pass. Your predeccessors have failed, but there has to be a way to bring the enemy down. The enemy will be unprepared for a strike from within.
              textSource: 
            mod_campaign_start__s_main_op_start_header:
              text: Start
              textSource: 
        overworld_memories:
          text:
            mod_campaign_progress__name:
              text: Campaign progress
              textSource: 
            mod_flag_hvt__name:
              text: High value target
              textSource: 
        overworld_quests:
          text:
            mod_liberation__s_01_main_a_header:
              text: All out
              textSource: 
            mod_liberation__s_01_main_a_text:
              text: You're cleared to engage any target. Hit the enemy where it hurts.
              textSource: 
            mod_liberation__s_01_main_cd_hvt_text:
              text: Take out all high value targets in the province.
              textSource: 
            mod_liberation__s_01_main_cd_main_text:
              text: Weaken the enemy by attacking secondary targets around the province.
              textSource: 
            mod_liberation__s_03_showdown_a_header:
              text: Showdown
              textSource: 
            mod_liberation__s_03_showdown_a_text:
              text: >-
                The enemy is barely holding on, with most of the occupation forces retreating to the last stronghold in the region.


                The frontline base is not available. All resistance forces have moved in to surround the enemy stronghold. It's time to join them.
              textSource: 
            mod_liberation__s_03_showdown_cd_main_text:
              text: Strike the enemy stronghold to finish the fight.
              textSource: 
            mod_liberation_a_header:
              text: Liberation
              textSource: 
            mod_liberation_a_text:
              text: Free the province from the invaders.
              textSource: 
        overworld_start:
          text:
            mod_start_01__header:
              text: Custom campaign
              textSource: 
            mod_start_01__sub:
              text: Lead an elite squad behind the enemy lines
              textSource: 
            mod_start_01__text:
              text: Start at the capital and blaze your way through Fyrland. Minimal campaign with streamlined liberations.
              textSource: 
assetBundles: 
libraryDLLs: 
extraFiles: 
