workshop:
  publishedID: 3626329642
  visibility: FriendsOnly
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: Minor update.
  tags:
  - Campaign
  - Overworld
  - Progression
  texPreviewUpload: true
configEdits:
  dataLinkers:
  - type: DataLinkerSettingsOverworld
    file:
      edits:
      - path: customStartAllowed
        value: true
        operation: Override
      - path: pointSpawnRangeDefault
        value: (0, 10000)
        operation: Override
  dataMultiLinkers:
  - type: DataMultiLinkerOverworldCampaignStart
    edits:
    - key: test
      removed: false
      edits:
      - path: hidden
        value: true
        operation: Override
  - type: DataMultiLinkerOverworldPointPreset
    edits:
    - key: generic_assassination
      removed: false
      edits:
      - path: tags
        value: mod_hvt !+
        operation: Override
    - key: generic_base_showdown
      removed: false
      edits:
      - path: tags
        value: mod_hvt !+
        operation: Override
    - key: generic_boss
      removed: false
      edits:
      - path: hidden
        value: true
        operation: Override
      - path: tags
        value: mod_hvt !+
        operation: Override
      - path: tags
        value: boss !+
        operation: Override
  - type: DataMultiLinkerOverworldProvinceBlueprints
    edits:
    - key: province_00
      removed: false
      edits:
      - path: tags
        value: mod_excluded !+
        operation: Override
    - key: province_breakthrough_line
      removed: false
      edits:
      - path: tags
        value: mod_excluded !+
        operation: Override
    - key: province_capital
      removed: false
      edits:
      - path: tags
        value: mod_excluded !+
        operation: Override
textEdits:
  languages:
    English:
      sectors:
        overworld_campaign:
          text:
            mod_campaign_01__header:
              text: Starting up
              textSource: 
            mod_campaign_01__text:
              text: Get your bearings and pick a destination.
              textSource: 
            mod_campaign_02__header:
              text: Punching through
              textSource: 
            mod_campaign_02__text:
              text: Keep hitting the enemy where it hurts. Advance through Fyrland to rendezvous with allied forces.
              textSource: 
            mod_campaign_03__header:
              text: Cleanup
              textSource: 
            mod_campaign_03__text:
              text: The enemy will try to counterattack and revert your gains. Keep up the pressure.
              textSource: 
        overworld_interaction:
          text:
            mod_campaign_arrival_01__s_step_01_main:
              text: One by one, red dots light up the map in the briefing room, warning about converging patrols and enemy positions. The base nears the frontline. They won't be able to stop you.
              textSource: 
            mod_campaign_frontline_additions__s_main_op_campaign_options_header:
              text: Campaign options
              textSource: 
            mod_campaign_liberation_01__s_step_01_main:
              text: The enemy is in full retreat. There is still much to be done, but that can come later. Your crew is in good spirits and is looking forward to a well deserved rest. A resistance outpost nearby should be a good place to stop.
              textSource: 
            mod_campaign_options__s_main_main:
              text: You turn your eyes away from the frontline outpost and focus on the screens in front of you.
              textSource: 
            mod_campaign_options__s_main_op_option_a_header:
              text: Advance research
              textSource: 
            mod_campaign_options__s_main_op_option_a_text:
              text: Invest some of the materials you have into the prediction system.
              textSource: 
            mod_campaign_start__s_main_header:
              text: RECEIVING INTEL...
              textSource: 
            mod_campaign_start__s_main_main:
              text: After days in the dark navigating the Northern Supercollider tunnels, your mobile base finally emerges into the light. You are deep behind enemy lines, the foot of the Keystone Mountains. Your predecessors have failed, but there has to be a way to bring the enemy down. They will be unprepared for a strike from within.
              textSource: 
            mod_campaign_start__s_main_op_start_header:
              text: Start
              textSource: 
        overworld_memories:
          text:
            mod_campaign_progress__name:
              text: Campaign progress
              textSource: 
            mod_flag_hvt__name:
              text: HVT
              textSource: 
        overworld_quests:
          text:
            mod_liberation__s_01_main_a_header:
              text: All out
              textSource: 
            mod_liberation__s_01_main_a_text:
              text: 'The resistance forces have relayed detailed intel about every target in the region. You can engage in any order: all that matters is overwhelming the enemy.'
              textSource: 
            mod_liberation__s_01_main_cd_hvt_text:
              text: >-
                [ff][sp=s_icon_l24_inv_empty2]   Objective 1
                         [cc]Take out enough high value targets to break the enemy morale[ff]
              textSource: 
            mod_liberation__s_01_main_cd_main_text:
              text: >-
                [ff][b9e7ff][sp=s_icon_l24_inv_repeat2]   Objective 2
                         [cc]Weaken the enemy by attacking secondary targets around the province[ff][-]
              textSource: 
            mod_liberation_a_header:
              text: Liberation
              textSource: 
            mod_liberation_a_text:
              text: Free the province from the invaders.
              textSource: 
        overworld_start:
          text:
            mod_start_01__header:
              text: Custom campaign
              textSource: 
            mod_start_01__sub:
              text: Lead an elite squad behind the enemy lines
              textSource: 
            mod_start_01__text:
              text: Start behind the enemy lines, take the enemy off guard and blaze your way through Fyrland. Minimal campaign with streamlined liberation objectives.
              textSource: 
assetBundles: 
libraryDLLs: 
extraFiles: 
